on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      env:
        GIT_TRACE: 1
        GIT_CURL_VERBOSE: 1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - run: npm i

    - run: npm run build

    - name: Build the Docker image
    run: |
      docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      docker build -t blog:latest .
      docker tag blog:latest jaywade/frst_lib:latest
      docker push jaywade/frst_lib:latest # 推送