name: Docker Image CI # Actions名称
on: 
  push:
    branches:
    - master
    
jobs:
  - name: ssh docker login # 使用appleboy/ssh-action@master登录服务器执行拉取镜像脚本，服务器ip、用户名、密码配置方式同容器镜像服务配置方式一样
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.SSH_HOST }} 
    username: ${{ secrets.SSH_USERNAME }}
    password: ${{ secrets.SSH_PASSWORD }}
    script: cd ~ && sh test.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}