name: Blog deploy
on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
    uses: actions/checkout@master
      - name:ssh aliyun login
uses: appleboy/ssh-action@master
with: 
        host: ${{ secrets.SSH_HOST }} 
        port: ${{ secrets.SSH_PORT }} 
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: cd ~ && sh test.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}